### ISSUE TITLE
Upgrade umami chart to v2

### ISSUE THREAD

**Issue by christianknell** [christianknell/helm-charts#651]
https://github.com/umami-software/umami/pkgs/container/umami

**Comment by jadolg** [comment]
Hi @christianknell 
I'm currently using your chart on my setup and trying to run with 2.8.0.
I'm still not done with it but one thing to be aware of is the migrations from v1 to v2.
They are not included in the image and they need to be run apart https://umami.is/docs/migrate-v1-v2

**Comment by christianknell** [comment]
Hey @jadolg thanks for pointing this out. Will try to integrate a Job that runs the migrations, which can be enabled once in the Helm Chart.

**Comment by jadolg** [comment]
btw, I managed to get it running (not without headaches).
First, I broke the migrations because I updated directly.
Then it started failing because it couldn't bind to a specific address in the cluster.
Turns out the hostname does more on v2 than it does on v1.
Removing the hostname completely solved the issue for me.
That's all. Things to have in mind.
Thanks for all the good work :100: :smiley:

**Comment by lefinal** [comment]
@christianknell do you have an estimation when we can expect v2 being available?

**Comment by christianknell** [comment]
@lefinal sorry for the late reply. Will work on this, this weekend.

**Comment by christianknell** [comment]
@lefinal and @jadolg: v2.0.0 is now released.

**Comment by lefinal** [comment]
> @lefinal and @jadolg: v2.0.0 is now released.

Awesome!! Thank you so much for the effort!
